--- 
title: "Predicción de precios del Bitcoin"
author: "José David Zamudio Rojas"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Este es un libro el cual desarrollara la prediccion del precio del Bitcoin en 2 periodos de tiempo"
---


# Justificación

## Justificación.

Dentro de los mercados financieros donde la volatilidad es parte de su naturaleza, el mercado de las criptomonedas sobresale por ser altamente voluble con alta incertidumbre en función de sus proyecciones y predicciones. Esto se da principalmente porque es un mercado no regulado que opera las 24 horas del día en los 7 días de la semana.

Según TradingView (s.f.), la dominancia de Bitcoin en el mercado de criptomonedas es de más del 50%, lo que lo hace el dominador del mercado. Es por ello, el interés de realizar el estudio de series de tiempo a esta criptomoneda desde un enfoque univariado.

Para este estudio se propone realizar análisis de series para 2 periodos de tiempo.

1. Periodo diario: Desde 01 de enero de 2022 al 13 de abril de 2025

2. Periodo de 5 minutos: Desde el 01 de enero de 2024 al 13 de abril de 2025.

## Fuente de información.

La fuente de información será el principal Exchange de criptomonedas llamado “Binance”, el cual, por medio de su API, permite descargar información histórica de los precios de las criptomonedas por periodos de tiempo definidos (minuto, hora, diario, etc.)

Para el propósito del presente estudio se descargará y procesará la información para crear 2 set de datos en formato CSV (uno por cada periodo definido anteriormente).
Respecto al uso de esta información es totalmente libre y el único requisito para su generación es contar con una cuenta en el Exchange y tener el API habilitada.
